name: MacOS Unit test

on: [push, pull_request]

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [macos-11.0]
          python-version: [3.8]
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install ICU
          run: |
            brew install icu4c
            curl -o PyICU-2.6.tar.gz https://files.pythonhosted.org/packages/31/46/fa08c8efae2951e67681ec24319f789fc1a74e2096dd74373e34c79319de/PyICU-2.6.tar.gz
            tar xvf PyICU-2.6.tar.gz
            cd PyICU-2.6
            LDFLAGS=-L/usr/local/opt/icu4c/lib CPPFLAGS=-I/usr/local/opt/icu4c/include python setup.py build
            python setup.py install
            cd ..
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install "h5py>=2.10.0,<3" "tensorflow>=2.3.1,<3"
            pip install torch==1.7.0
            pip install deepcut
            pip install .[full]
        - name: Test
          run: |
            python setup.py test